# src/Resources/config/packages/sitemap.yaml
# This file is copied to your application's config/packages directory when
# running "php bin/console sitemap:install".

sitemap:
    # Default configuration for SitemapBundle
    default_priority: null
    default_changefreq: null
    hosts:
        default:
            path: '/sitemap.xml'
            groups:
                default:
                    path: null
                    lastmod: null
