# src/Resources/config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  jgniecki\SitemapBundle\:
    resource: '../../*'
    exclude:
      - '../../Entity/'
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../SitemapBundle.php'

  jgniecki\SitemapBundle\Sitemap\SitemapGenerator:
    arguments:
      - '@router'
      - !tagged_iterator sitemap.resolver
      - '%sitemap.hosts%'

  jgniecki\SitemapBundle\Routing\SitemapRouteLoader:
    arguments:
      $hosts: '%sitemap.hosts%'
    tags:
      - { name: routing.loader }

  jgniecki\SitemapBundle\Controller\SitemapController:
    public: true
    tags: ['controller.service_arguments']
    arguments:
      - '@jgniecki\SitemapBundle\Sitemap\SitemapGenerator'
      - '@twig'

  _instanceof:
    jgniecki\SitemapBundle\Sitemap\Interface\RouteResolverInterface:
      tags: ['sitemap.resolver']